### ISSUE TITLE
Customizer Beta

### ISSUE THREAD

**Issue by JQOz** [reduxframework/redux-framework-4#10]
Hi,

I see "Customizer Beta" on Redux-Demo. Also the typography is available there. How can i use it. If i activate Customizer as true i see no typography options on the Customizer-Sidebar. I tried this with Redux 3x and Redux 4

Regards

**Comment by kprovance** [comment]
Short version:  You cannot.  Only basic fields are supported from the Redux core. THe reason you see all the fields on the demo is because the Advanced Customizer extension is active.  I can turn that off.  It's not available for v3.  It will be part of Redux Pro.  No ETA on when that will be available or ready.  Sorry for the misunderstanding.
