### ISSUE TITLE
Output Argument

### ISSUE THREAD

**Issue by visualmodo** [reduxframework/redux-framework-4#16]
This option is extremely important for a project and I always make use of it.

As CSS increases its cascading effect it becomes difficult or even impossible to overlay the CSS that comes from the Redux Framework Output because it does not have the "!important" option.

Please implement in Redux V4 the possibility of adding "!important" in the output argument.

Ex:

'output-priority' => false,    =   color: red;
'output-priority' => true,    =   color: red !important;

Thanks and have a great day :)

**Comment by kprovance** [comment]
That's a complicated piece of code to inject into the current output array, maintain backward comap, and then actually make it work.  It is something I would be willing to do for Redux Pro and will put it on my trello board.  This way devs would pay up, as we need them to do.

Redux 4 is feature complete.  There will be no new features added at this point.  This is so we can offer premium products and services.  We need to do this in order to afford to exist.  

Thanks!

**Comment by visualmodo** [comment]
Many thanks for the reply!

I understand perfectly you. If you add this option in the Redux PRO version, I will definitely buy it.
