### ISSUE TITLE
Limit the locations where redux-framework notifications are shown

### ISSUE THREAD

**Issue by richboos** [reduxframework/redux-framework-4#43]
When I was in the WordPress Admin area I noticed many different page types had a notice letting me know redux v4 was coming soon. I tweeted about this and was told to bring up the issue on github so hopefully I picked the right place.

My suggestion is to limit this only a few locations in the admin area. And, restrict it to certain user types (if it isn't already). This suggestion is inspired by the WordPress plugin guidelines. For example, if say the PayPal Express plugin is getting an update soon, we shouldn't see that notice while approving product reviews.

That is all. I had either dismissed the notice or picked the wrong site, so I can't provide screenshots. Sorry if it sounds like I am nagging. Communication is good but effective communication is better. Too many notifications create a boy who cried wolf scenario. And unrelated notifications (approving comments example above) is not good either.

**Comment by dovy** [comment]
@richboos we try very much to limit the notifications we have.

- At plugin notification
- On errors
- Redux notification

I am guessing you're mentioning the Redux notification, which we limit to the open panel or a page using Redux Metaboxes. It's hard to say we'll only show on "Redux pages" because Redux covers so much. Take the customizer for example, how would you notify anyone?!

Rest assured these things ONLY show up when you use dev_mode enabled, WP_DEBUG set to true, or you're running locally. The rest of the time, all is hidden.

If you have other ideas on how we can limit, but still notify developers on occasion, I'd appreciate the insight. Unfortunately, WordPress.org does not permit us contacting our user base, and beyond that, we only wish to contact the developers with these notifications.

I very much aim to comply in all things, but we're not a theme or plugin. We're a framework used by both. So our notifications need to be thought of accordingly.

Again, I am willing to have a discussion. Let me know your thoughts.

**Comment by richboos** [comment]
Hey dovy, sorry for the delay in responding. I see what you mean.

Seems like you are already doing what you can and likely thought of everything. I'll keep this in mind and if there is something I or my colleagues think of that could be a good idea, I'll let you know.

**Comment by dovy** [comment]
Thank you for understanding. Have a great day.
