### ISSUE TITLE
File field_typography.json contains PHP code

### ISSUE THREAD

**Issue by IgorCode** [reduxframework/redux-framework-4#47]
File [field_typography.json](https://github.com/reduxframework/redux-framework-4/blob/master/ReduxCore/inc/fields/typography/todo/field_typography.json) contains PHP code, not JSON, I assume it's an error and file should be deleted?

It's also present in main `redux-framework` repo.

**Comment by dovy** [comment]
Ha, you found some old "dirt" as it were. This was a reworking of the entire typography field to use a single input value. There was a minor bug that was never resolved. Rather than deleting the code, it was renamed. I should go back to repair it so the benefits can be brought into 4. Good reminder. I'm going to leave this note here as a reminder. Thank you.

**Comment by dovy** [comment]
Finally got around to removing this.
