### ISSUE TITLE
Themes to test against

### ISSUE THREAD

**Issue by dovy** [reduxframework/redux-framework-4#81]
- [ ] https://themeforest.net/item/wp-pro-real-estate-7-responsive-real-estate-wordpress-theme/12473778
- [x] Avada (Drop in ReduxCore?)
- [ ] https://themeforest.net/item/dante-responsive-multipurpose-wordpress-theme/6175269
- [ ] https://themeforest.net/item/wp-pro-real-estate-7-responsive-real-estate-wordpress-theme/12473778
- [ ] https://themeforest.net/item/907-responsive-multipurpose-wordpress-theme/4087140
- [ ] https://themeforest.net/item/wplms-learning-management-system/6780226
- [x] https://wordpress.org/themes/virtue/
- [x] https://wordpress.org/themes/pinnacle/
- [ ] https://themeforest.net/item/salient-responsive-multipurpose-theme/4363266
- [ ] https://themeforest.net/item/the-ken-multipurpose-creative-wordpress-theme-/7281173
- [ ] https://themeforest.net/item/border-a-delightful-photography-wordpress-theme/6920241

**Comment by kprovance** [comment]
Avada rebranded everything, and rewrote a bunch of stuff.

**Comment by dovy** [comment]
I'm not too stressed about Avada, but it would be a great compatibility test. To make sure old code still works. Just a thought.

**Comment by kprovance** [comment]
Virtue and Pinnacle load up fine.  I see only one issue with the Kadence slider extension, in that they are using a VERY old boilerplate that tried to extend ReduxFramework, which never worked.  That's causing a notice.  He'll have to fix that by changing `$this->args['opt_name']` to `$this->$parent->args['opt_name']`.  It should never have worked.  But I figure since this is an embed job, devs should be running their own tests anyway and should catch this,
